name: MS Teams Notification
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Send MS Teams notification
        uses: dchourasia/ms-teams-notification@1.0 
        if: always() # Send notification regardless of job status
        with:
          github-token: ${{ github.token }}
          webhook-uri: ${{ secrets.TEAMS_WEBHOOK_URL }}
